[package]
name = "hammerspace"
description = "A plugin for loading and debugging gltf scenes"
repository = "https://github.com/KyleWinston/hammerspace"
version = "0.1.12"
authors = ["Ky Roberts", "Ky Roberts<kywinston@proton.me>"]
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[features]
metrics = ["lightyear/metrics", "dep:metrics-exporter-prometheus"]
mock_time = ["lightyear/mock_time"]

[dependencies]
async-compat = "0.2.3"
lightyear = { version = "0.13.0", features = [
    "steam",
    "render",
    "webtransport",
    "websocket",
] }
tracing = "0.1"
tracing-subscriber = "0.3.17"
rand = "0.8.1"
anyhow = { version = "1.0.75", features = [] }
mock_instant = "0.4"
metrics-exporter-prometheus = { version = "0.13.0", optional = true }
derive_more = { version = "0.99", features = ["add", "mul"] }
bevy = { version = "0.13.2", features = ["bevy_core_pipeline"] }
bevy_third_person_camera = "0.1.10"
bevy_rapier3d = "0.25.0"
serde = { version = "1.0.188", features = ["derive"] }
clap = { version = "4.4", features = ["derive"] }
cfg-if = "1.0.0"
crossbeam-channel = "0.5.11"
bevy-inspector-egui = "0.23"

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
