[package]
name = "hammerspace"
description = "A plugin for loading and debugging gltf scenes"
repository = "https://github.com/KyleWinston/hammerspace"
version = "0.1.16"
authors = ["Ky Roberts", "Ky Roberts<kywinston@proton.me>"]
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]
resolver = "2"

[features]
metrics = ["lightyear/metrics", "dep:metrics-exporter-prometheus"]
mock_time = ["lightyear/mock_time"]
handle-physics = ["bevy_rapier3d"]
level-loader = []
multiplayer = [
    "lightyear",
    "serde",
    "clap",
    "crossbeam-channel",
    "derive_more",
    "tracing",
    "tracing-subscriber",
    "mock_instant"
]
debug = []

[dependencies]
mock_instant = { version = "0.4", optional = true }
lightyear = { version = "0.13.0", optional = true, features = [
    "steam",
    "render",
    "webtransport",
    "websocket",
] }
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3.17", optional = true }
rand = "0.8.1"
anyhow = { version = "1.0.75", features = [], optional = true }
metrics-exporter-prometheus = { version = "0.13.0", optional = true }
derive_more = { version = "0.99", features = ["add", "mul"], optional = true }
bevy = { version = "0.13.2", features = ["bevy_core_pipeline"] }
bevy_third_person_camera = "0.1.10"
bevy_rapier3d = { version = "0.25.0", optional = true }
serde = { version = "1.0.188", optional = true, features = ["derive"] }
clap = { version = "4.4", optional = true, features = ["derive"] }
cfg-if = "1.0.0"
crossbeam-channel = { version = "0.5.11", optional = true }
bevy-inspector-egui = { version = "0.23" }
async-compat = "0.2.3"

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
