[package]
name = "hammerspace"
description = "A plugin for loading and debugging gltf scenes"

repository = "https://github.com/KyWinston/hammerspace"
version = "0.1.29"

authors = ["Ky Roberts", "Ky Roberts<kywinston@proton.me>"]
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]
resolver = "2"

[dependencies]
async-executor = "1.12.0"
bevy = { workspace = true, default-features = false, features = [
    "multi-threaded",  # Run with multithreading
    "bevy_asset",      # Assets management
    "bevy_scene",      # Scenes management
    "bevy_gltf",       # GLTF 3D assets format support
    "dynamic_linking",
    "asset_processor", # Asset processing
] }
# bevy = { git = "https://github.com/bevyengine/bevy", branch = "release-0.14.0", features = [
#     "bevy_asset",      # Assets management
#     "bevy_scene",      # Scenes management
#     "bevy_gltf",       # GLTF 3D assets format support
#     "asset_processor", # Asset processing
# ] }
bevy_rapier3d = { workspace = true }

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
opt-level = "z"
strip = true
lto = true
