[package]
name = "hammerspace"
description = "A plugin for loading and debugging gltf scenes"
repository = "https://github.com/KyleWinston/hammerspace"
version = "0.1.27"
authors = ["Ky Roberts", "Ky Roberts<kywinston@proton.me>"]
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]
resolver = "2"

[dependencies]
alkyd = "0.1.11"
bevy = { version = "0.13.2", features = [
    "bevy_core_pipeline",
    "dynamic_linking",
] }
bevy_rapier3d = "0.25.0"
bevy_third_person_camera = "0.1.10"

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
