[package]
name = "hammerspace"
description = "A plugin for the loading and management of levels and scenes, and their physical properties"
repository = "https://github.com/KyWinston/hammerspace"
version = "0.1.30"
authors = ["Ky Winston<kwinston@proton.me>"]
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]
publish = true

[dependencies]
async-executor = "1.12.0"
bevy = { version = "0.14", default-features = false, features = [
    "bevy_asset",         # Assets management
    "bevy_scene",         # Scenes management
    "bevy_core_pipeline",
    "bevy_winit",
    "x11",
    "bevy_gltf",          # GLTF 3D assets format support
    "asset_processor",    # Asset processing
] }
avian3d = "0.1.0"
vleue_navigator = "0.8.0-rc.3"

[dev-dependencies]
bevy_quill_obsidian = "0.1.0"
bevy_panorbit_camera = "0.19.1"
bevy_gltf_components = "0.5.1"
bevy_gltf_blueprints = "0.10.2"
bevy_gltf_save_load = "0.4.1"
bevy_registry_export = "0.3.1"
