version: 2.1


# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current
    steps:
      - Install stable toolchain
      - run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 
      - run: rustup update stable && rustup default stable
      - run: cargo build --release
  test:
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current
    steps:
      - Rust cargo test

      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test



# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build